name: fl_place_autocomplete_platform_interface
description: "Platform interface for the fl_place_autocomplete plugin."
version: 0.1.0
homepage: https://github.com/mk7/fl_place_autocomplete
repository: https://github.com/mk7/fl_place_autocomplete/tree/main/fl_place_autocomplete_platform_interface
issue_tracker: https://github.com/mk7/fl_place_autocomplete/issues
topics:
  - google-places
  - places
  - autocomplete

environment:
  sdk: ^3.13.0
  flutter: ">=3.44.0"
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.19.0
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  pigeon: ^29.0.0
