// Autogenerated from Pigeon (v29.0.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.mk7.fl_place_autocomplete_android

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
private object MessagesPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Generated class from Pigeon that represents data sent in messages. */
data class LatLngMsg (
  val latitude: Double,
  val longitude: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LatLngMsg {
      val latitude = pigeonVar_list[0] as Double
      val longitude = pigeonVar_list[1] as Double
      return LatLngMsg(latitude, longitude)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      latitude,
      longitude,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as LatLngMsg
    return MessagesPigeonUtils.deepEquals(this.latitude, other.latitude) && MessagesPigeonUtils.deepEquals(this.longitude, other.longitude)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.latitude)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.longitude)
    return result
  }
  override fun toString(): String {
    return "LatLngMsg(latitude=$latitude, longitude=$longitude)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class LatLngBoundsMsg (
  val southwest: LatLngMsg,
  val northeast: LatLngMsg
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LatLngBoundsMsg {
      val southwest = pigeonVar_list[0] as LatLngMsg
      val northeast = pigeonVar_list[1] as LatLngMsg
      return LatLngBoundsMsg(southwest, northeast)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      southwest,
      northeast,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as LatLngBoundsMsg
    return MessagesPigeonUtils.deepEquals(this.southwest, other.southwest) && MessagesPigeonUtils.deepEquals(this.northeast, other.northeast)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.southwest)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.northeast)
    return result
  }
  override fun toString(): String {
    return "LatLngBoundsMsg(southwest=$southwest, northeast=$northeast)"
  }
}

/**
 * Circle when [center] != null, rectangle when [bounds] != null.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class AreaMsg (
  val center: LatLngMsg? = null,
  val radiusMeters: Double? = null,
  val bounds: LatLngBoundsMsg? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AreaMsg {
      val center = pigeonVar_list[0] as LatLngMsg?
      val radiusMeters = pigeonVar_list[1] as Double?
      val bounds = pigeonVar_list[2] as LatLngBoundsMsg?
      return AreaMsg(center, radiusMeters, bounds)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      center,
      radiusMeters,
      bounds,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AreaMsg
    return MessagesPigeonUtils.deepEquals(this.center, other.center) && MessagesPigeonUtils.deepEquals(this.radiusMeters, other.radiusMeters) && MessagesPigeonUtils.deepEquals(this.bounds, other.bounds)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.center)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.radiusMeters)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.bounds)
    return result
  }
  override fun toString(): String {
    return "AreaMsg(center=$center, radiusMeters=$radiusMeters, bounds=$bounds)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class OptionsMsg (
  val locationBias: AreaMsg? = null,
  val locationRestriction: LatLngBoundsMsg? = null,
  val origin: LatLngMsg? = null,
  val includedPrimaryTypes: List<String>,
  val includedRegionCodes: List<String>,
  val languageCode: String? = null,
  val regionCode: String? = null,
  val inputOffset: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): OptionsMsg {
      val locationBias = pigeonVar_list[0] as AreaMsg?
      val locationRestriction = pigeonVar_list[1] as LatLngBoundsMsg?
      val origin = pigeonVar_list[2] as LatLngMsg?
      val includedPrimaryTypes = pigeonVar_list[3] as List<String>
      val includedRegionCodes = pigeonVar_list[4] as List<String>
      val languageCode = pigeonVar_list[5] as String?
      val regionCode = pigeonVar_list[6] as String?
      val inputOffset = pigeonVar_list[7] as Long?
      return OptionsMsg(locationBias, locationRestriction, origin, includedPrimaryTypes, includedRegionCodes, languageCode, regionCode, inputOffset)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      locationBias,
      locationRestriction,
      origin,
      includedPrimaryTypes,
      includedRegionCodes,
      languageCode,
      regionCode,
      inputOffset,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as OptionsMsg
    return MessagesPigeonUtils.deepEquals(this.locationBias, other.locationBias) && MessagesPigeonUtils.deepEquals(this.locationRestriction, other.locationRestriction) && MessagesPigeonUtils.deepEquals(this.origin, other.origin) && MessagesPigeonUtils.deepEquals(this.includedPrimaryTypes, other.includedPrimaryTypes) && MessagesPigeonUtils.deepEquals(this.includedRegionCodes, other.includedRegionCodes) && MessagesPigeonUtils.deepEquals(this.languageCode, other.languageCode) && MessagesPigeonUtils.deepEquals(this.regionCode, other.regionCode) && MessagesPigeonUtils.deepEquals(this.inputOffset, other.inputOffset)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.locationBias)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.locationRestriction)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.origin)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.includedPrimaryTypes)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.includedRegionCodes)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.languageCode)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.regionCode)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.inputOffset)
    return result
  }
  override fun toString(): String {
    return "OptionsMsg(locationBias=$locationBias, locationRestriction=$locationRestriction, origin=$origin, includedPrimaryTypes=$includedPrimaryTypes, includedRegionCodes=$includedRegionCodes, languageCode=$languageCode, regionCode=$regionCode, inputOffset=$inputOffset)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class MatchedRangeMsg (
  val start: Long,
  val end: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MatchedRangeMsg {
      val start = pigeonVar_list[0] as Long
      val end = pigeonVar_list[1] as Long
      return MatchedRangeMsg(start, end)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      start,
      end,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as MatchedRangeMsg
    return MessagesPigeonUtils.deepEquals(this.start, other.start) && MessagesPigeonUtils.deepEquals(this.end, other.end)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.start)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.end)
    return result
  }
  override fun toString(): String {
    return "MatchedRangeMsg(start=$start, end=$end)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PredictionMsg (
  val placeId: String,
  val fullText: String,
  val primaryText: String,
  val secondaryText: String,
  val matchedRanges: List<MatchedRangeMsg>,
  val types: List<String>,
  val distanceMeters: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PredictionMsg {
      val placeId = pigeonVar_list[0] as String
      val fullText = pigeonVar_list[1] as String
      val primaryText = pigeonVar_list[2] as String
      val secondaryText = pigeonVar_list[3] as String
      val matchedRanges = pigeonVar_list[4] as List<MatchedRangeMsg>
      val types = pigeonVar_list[5] as List<String>
      val distanceMeters = pigeonVar_list[6] as Long?
      return PredictionMsg(placeId, fullText, primaryText, secondaryText, matchedRanges, types, distanceMeters)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      placeId,
      fullText,
      primaryText,
      secondaryText,
      matchedRanges,
      types,
      distanceMeters,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PredictionMsg
    return MessagesPigeonUtils.deepEquals(this.placeId, other.placeId) && MessagesPigeonUtils.deepEquals(this.fullText, other.fullText) && MessagesPigeonUtils.deepEquals(this.primaryText, other.primaryText) && MessagesPigeonUtils.deepEquals(this.secondaryText, other.secondaryText) && MessagesPigeonUtils.deepEquals(this.matchedRanges, other.matchedRanges) && MessagesPigeonUtils.deepEquals(this.types, other.types) && MessagesPigeonUtils.deepEquals(this.distanceMeters, other.distanceMeters)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.placeId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.fullText)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.primaryText)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.secondaryText)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.matchedRanges)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.types)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.distanceMeters)
    return result
  }
  override fun toString(): String {
    return "PredictionMsg(placeId=$placeId, fullText=$fullText, primaryText=$primaryText, secondaryText=$secondaryText, matchedRanges=$matchedRanges, types=$types, distanceMeters=$distanceMeters)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class AddressComponentMsg (
  val longText: String? = null,
  val shortText: String? = null,
  val types: List<String>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AddressComponentMsg {
      val longText = pigeonVar_list[0] as String?
      val shortText = pigeonVar_list[1] as String?
      val types = pigeonVar_list[2] as List<String>
      return AddressComponentMsg(longText, shortText, types)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      longText,
      shortText,
      types,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AddressComponentMsg
    return MessagesPigeonUtils.deepEquals(this.longText, other.longText) && MessagesPigeonUtils.deepEquals(this.shortText, other.shortText) && MessagesPigeonUtils.deepEquals(this.types, other.types)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.longText)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.shortText)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.types)
    return result
  }
  override fun toString(): String {
    return "AddressComponentMsg(longText=$longText, shortText=$shortText, types=$types)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class TimePointMsg (
  val day: Long,
  val hour: Long,
  val minute: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): TimePointMsg {
      val day = pigeonVar_list[0] as Long
      val hour = pigeonVar_list[1] as Long
      val minute = pigeonVar_list[2] as Long
      return TimePointMsg(day, hour, minute)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      day,
      hour,
      minute,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as TimePointMsg
    return MessagesPigeonUtils.deepEquals(this.day, other.day) && MessagesPigeonUtils.deepEquals(this.hour, other.hour) && MessagesPigeonUtils.deepEquals(this.minute, other.minute)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.day)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.hour)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.minute)
    return result
  }
  override fun toString(): String {
    return "TimePointMsg(day=$day, hour=$hour, minute=$minute)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class OpeningPeriodMsg (
  val open: TimePointMsg? = null,
  val close: TimePointMsg? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): OpeningPeriodMsg {
      val open = pigeonVar_list[0] as TimePointMsg?
      val close = pigeonVar_list[1] as TimePointMsg?
      return OpeningPeriodMsg(open, close)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      open,
      close,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as OpeningPeriodMsg
    return MessagesPigeonUtils.deepEquals(this.open, other.open) && MessagesPigeonUtils.deepEquals(this.close, other.close)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.open)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.close)
    return result
  }
  override fun toString(): String {
    return "OpeningPeriodMsg(open=$open, close=$close)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class OpeningHoursMsg (
  val weekdayDescriptions: List<String>,
  val periods: List<OpeningPeriodMsg>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): OpeningHoursMsg {
      val weekdayDescriptions = pigeonVar_list[0] as List<String>
      val periods = pigeonVar_list[1] as List<OpeningPeriodMsg>
      return OpeningHoursMsg(weekdayDescriptions, periods)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      weekdayDescriptions,
      periods,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as OpeningHoursMsg
    return MessagesPigeonUtils.deepEquals(this.weekdayDescriptions, other.weekdayDescriptions) && MessagesPigeonUtils.deepEquals(this.periods, other.periods)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.weekdayDescriptions)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.periods)
    return result
  }
  override fun toString(): String {
    return "OpeningHoursMsg(weekdayDescriptions=$weekdayDescriptions, periods=$periods)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class AuthorAttributionMsg (
  val displayName: String? = null,
  val uri: String? = null,
  val photoUri: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AuthorAttributionMsg {
      val displayName = pigeonVar_list[0] as String?
      val uri = pigeonVar_list[1] as String?
      val photoUri = pigeonVar_list[2] as String?
      return AuthorAttributionMsg(displayName, uri, photoUri)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      displayName,
      uri,
      photoUri,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AuthorAttributionMsg
    return MessagesPigeonUtils.deepEquals(this.displayName, other.displayName) && MessagesPigeonUtils.deepEquals(this.uri, other.uri) && MessagesPigeonUtils.deepEquals(this.photoUri, other.photoUri)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.displayName)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.uri)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.photoUri)
    return result
  }
  override fun toString(): String {
    return "AuthorAttributionMsg(displayName=$displayName, uri=$uri, photoUri=$photoUri)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PhotoRefMsg (
  val id: String,
  val widthPx: Long? = null,
  val heightPx: Long? = null,
  val authorAttributions: List<AuthorAttributionMsg>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PhotoRefMsg {
      val id = pigeonVar_list[0] as String
      val widthPx = pigeonVar_list[1] as Long?
      val heightPx = pigeonVar_list[2] as Long?
      val authorAttributions = pigeonVar_list[3] as List<AuthorAttributionMsg>
      return PhotoRefMsg(id, widthPx, heightPx, authorAttributions)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      widthPx,
      heightPx,
      authorAttributions,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PhotoRefMsg
    return MessagesPigeonUtils.deepEquals(this.id, other.id) && MessagesPigeonUtils.deepEquals(this.widthPx, other.widthPx) && MessagesPigeonUtils.deepEquals(this.heightPx, other.heightPx) && MessagesPigeonUtils.deepEquals(this.authorAttributions, other.authorAttributions)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.id)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.widthPx)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.heightPx)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.authorAttributions)
    return result
  }
  override fun toString(): String {
    return "PhotoRefMsg(id=$id, widthPx=$widthPx, heightPx=$heightPx, authorAttributions=$authorAttributions)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ReviewMsg (
  val authorAttribution: AuthorAttributionMsg? = null,
  val rating: Double? = null,
  val text: String? = null,
  val relativePublishTimeDescription: String? = null,
  val publishTime: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ReviewMsg {
      val authorAttribution = pigeonVar_list[0] as AuthorAttributionMsg?
      val rating = pigeonVar_list[1] as Double?
      val text = pigeonVar_list[2] as String?
      val relativePublishTimeDescription = pigeonVar_list[3] as String?
      val publishTime = pigeonVar_list[4] as String?
      return ReviewMsg(authorAttribution, rating, text, relativePublishTimeDescription, publishTime)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      authorAttribution,
      rating,
      text,
      relativePublishTimeDescription,
      publishTime,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ReviewMsg
    return MessagesPigeonUtils.deepEquals(this.authorAttribution, other.authorAttribution) && MessagesPigeonUtils.deepEquals(this.rating, other.rating) && MessagesPigeonUtils.deepEquals(this.text, other.text) && MessagesPigeonUtils.deepEquals(this.relativePublishTimeDescription, other.relativePublishTimeDescription) && MessagesPigeonUtils.deepEquals(this.publishTime, other.publishTime)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.authorAttribution)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.rating)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.text)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.relativePublishTimeDescription)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.publishTime)
    return result
  }
  override fun toString(): String {
    return "ReviewMsg(authorAttribution=$authorAttribution, rating=$rating, text=$text, relativePublishTimeDescription=$relativePublishTimeDescription, publishTime=$publishTime)"
  }
}

/**
 * All fields optional; only requested fields are populated.
 * priceLevel: free|inexpensive|moderate|expensive|veryExpensive.
 * businessStatus: operational|closedTemporarily|closedPermanently.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PlaceMsg (
  val id: String? = null,
  val displayName: String? = null,
  val formattedAddress: String? = null,
  val shortFormattedAddress: String? = null,
  val location: LatLngMsg? = null,
  val viewport: LatLngBoundsMsg? = null,
  val addressComponents: List<AddressComponentMsg>? = null,
  val types: List<String>? = null,
  val primaryType: String? = null,
  val primaryTypeDisplayName: String? = null,
  val rating: Double? = null,
  val userRatingCount: Long? = null,
  val priceLevel: String? = null,
  val nationalPhoneNumber: String? = null,
  val internationalPhoneNumber: String? = null,
  val websiteUri: String? = null,
  val googleMapsUri: String? = null,
  val utcOffsetMinutes: Long? = null,
  val businessStatus: String? = null,
  val editorialSummary: String? = null,
  val regularOpeningHours: OpeningHoursMsg? = null,
  val photos: List<PhotoRefMsg>? = null,
  val reviews: List<ReviewMsg>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PlaceMsg {
      val id = pigeonVar_list[0] as String?
      val displayName = pigeonVar_list[1] as String?
      val formattedAddress = pigeonVar_list[2] as String?
      val shortFormattedAddress = pigeonVar_list[3] as String?
      val location = pigeonVar_list[4] as LatLngMsg?
      val viewport = pigeonVar_list[5] as LatLngBoundsMsg?
      val addressComponents = pigeonVar_list[6] as List<AddressComponentMsg>?
      val types = pigeonVar_list[7] as List<String>?
      val primaryType = pigeonVar_list[8] as String?
      val primaryTypeDisplayName = pigeonVar_list[9] as String?
      val rating = pigeonVar_list[10] as Double?
      val userRatingCount = pigeonVar_list[11] as Long?
      val priceLevel = pigeonVar_list[12] as String?
      val nationalPhoneNumber = pigeonVar_list[13] as String?
      val internationalPhoneNumber = pigeonVar_list[14] as String?
      val websiteUri = pigeonVar_list[15] as String?
      val googleMapsUri = pigeonVar_list[16] as String?
      val utcOffsetMinutes = pigeonVar_list[17] as Long?
      val businessStatus = pigeonVar_list[18] as String?
      val editorialSummary = pigeonVar_list[19] as String?
      val regularOpeningHours = pigeonVar_list[20] as OpeningHoursMsg?
      val photos = pigeonVar_list[21] as List<PhotoRefMsg>?
      val reviews = pigeonVar_list[22] as List<ReviewMsg>?
      return PlaceMsg(id, displayName, formattedAddress, shortFormattedAddress, location, viewport, addressComponents, types, primaryType, primaryTypeDisplayName, rating, userRatingCount, priceLevel, nationalPhoneNumber, internationalPhoneNumber, websiteUri, googleMapsUri, utcOffsetMinutes, businessStatus, editorialSummary, regularOpeningHours, photos, reviews)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      displayName,
      formattedAddress,
      shortFormattedAddress,
      location,
      viewport,
      addressComponents,
      types,
      primaryType,
      primaryTypeDisplayName,
      rating,
      userRatingCount,
      priceLevel,
      nationalPhoneNumber,
      internationalPhoneNumber,
      websiteUri,
      googleMapsUri,
      utcOffsetMinutes,
      businessStatus,
      editorialSummary,
      regularOpeningHours,
      photos,
      reviews,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PlaceMsg
    return MessagesPigeonUtils.deepEquals(this.id, other.id) && MessagesPigeonUtils.deepEquals(this.displayName, other.displayName) && MessagesPigeonUtils.deepEquals(this.formattedAddress, other.formattedAddress) && MessagesPigeonUtils.deepEquals(this.shortFormattedAddress, other.shortFormattedAddress) && MessagesPigeonUtils.deepEquals(this.location, other.location) && MessagesPigeonUtils.deepEquals(this.viewport, other.viewport) && MessagesPigeonUtils.deepEquals(this.addressComponents, other.addressComponents) && MessagesPigeonUtils.deepEquals(this.types, other.types) && MessagesPigeonUtils.deepEquals(this.primaryType, other.primaryType) && MessagesPigeonUtils.deepEquals(this.primaryTypeDisplayName, other.primaryTypeDisplayName) && MessagesPigeonUtils.deepEquals(this.rating, other.rating) && MessagesPigeonUtils.deepEquals(this.userRatingCount, other.userRatingCount) && MessagesPigeonUtils.deepEquals(this.priceLevel, other.priceLevel) && MessagesPigeonUtils.deepEquals(this.nationalPhoneNumber, other.nationalPhoneNumber) && MessagesPigeonUtils.deepEquals(this.internationalPhoneNumber, other.internationalPhoneNumber) && MessagesPigeonUtils.deepEquals(this.websiteUri, other.websiteUri) && MessagesPigeonUtils.deepEquals(this.googleMapsUri, other.googleMapsUri) && MessagesPigeonUtils.deepEquals(this.utcOffsetMinutes, other.utcOffsetMinutes) && MessagesPigeonUtils.deepEquals(this.businessStatus, other.businessStatus) && MessagesPigeonUtils.deepEquals(this.editorialSummary, other.editorialSummary) && MessagesPigeonUtils.deepEquals(this.regularOpeningHours, other.regularOpeningHours) && MessagesPigeonUtils.deepEquals(this.photos, other.photos) && MessagesPigeonUtils.deepEquals(this.reviews, other.reviews)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.id)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.displayName)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.formattedAddress)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.shortFormattedAddress)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.location)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.viewport)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.addressComponents)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.types)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.primaryType)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.primaryTypeDisplayName)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.rating)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.userRatingCount)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.priceLevel)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.nationalPhoneNumber)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.internationalPhoneNumber)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.websiteUri)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.googleMapsUri)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.utcOffsetMinutes)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.businessStatus)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.editorialSummary)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.regularOpeningHours)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.photos)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.reviews)
    return result
  }
  override fun toString(): String {
    return "PlaceMsg(id=$id, displayName=$displayName, formattedAddress=$formattedAddress, shortFormattedAddress=$shortFormattedAddress, location=$location, viewport=$viewport, addressComponents=$addressComponents, types=$types, primaryType=$primaryType, primaryTypeDisplayName=$primaryTypeDisplayName, rating=$rating, userRatingCount=$userRatingCount, priceLevel=$priceLevel, nationalPhoneNumber=$nationalPhoneNumber, internationalPhoneNumber=$internationalPhoneNumber, websiteUri=$websiteUri, googleMapsUri=$googleMapsUri, utcOffsetMinutes=$utcOffsetMinutes, businessStatus=$businessStatus, editorialSummary=$editorialSummary, regularOpeningHours=$regularOpeningHours, photos=$photos, reviews=$reviews)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PhotoDataMsg (
  val bytes: ByteArray? = null,
  val uri: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PhotoDataMsg {
      val bytes = pigeonVar_list[0] as ByteArray?
      val uri = pigeonVar_list[1] as String?
      return PhotoDataMsg(bytes, uri)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      bytes,
      uri,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PhotoDataMsg
    return MessagesPigeonUtils.deepEquals(this.bytes, other.bytes) && MessagesPigeonUtils.deepEquals(this.uri, other.uri)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.bytes)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.uri)
    return result
  }
  override fun toString(): String {
    return "PhotoDataMsg(bytes=${bytes?.contentToString()}, uri=$uri)"
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LatLngMsg.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LatLngBoundsMsg.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AreaMsg.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          OptionsMsg.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MatchedRangeMsg.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PredictionMsg.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AddressComponentMsg.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TimePointMsg.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          OpeningPeriodMsg.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          OpeningHoursMsg.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AuthorAttributionMsg.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PhotoRefMsg.fromList(it)
        }
      }
      141.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ReviewMsg.fromList(it)
        }
      }
      142.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlaceMsg.fromList(it)
        }
      }
      143.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PhotoDataMsg.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is LatLngMsg -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is LatLngBoundsMsg -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is AreaMsg -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is OptionsMsg -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is MatchedRangeMsg -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is PredictionMsg -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is AddressComponentMsg -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is TimePointMsg -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is OpeningPeriodMsg -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is OpeningHoursMsg -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is AuthorAttributionMsg -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is PhotoRefMsg -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      is ReviewMsg -> {
        stream.write(141)
        writeValue(stream, value.toList())
      }
      is PlaceMsg -> {
        stream.write(142)
        writeValue(stream, value.toList())
      }
      is PhotoDataMsg -> {
        stream.write(143)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface PlacesHostApi {
  /**
   * Initializes the native SDK once, before the first Places call.
   *
   * [apiKey] is the key resolved from `--dart-define` (null when none was
   * given); a null/blank value falls back to the native configuration
   * (AndroidManifest meta-data / Info.plist). Throws
   * FlutterError(invalidApiKey) when no key is found anywhere.
   */
  suspend fun initialize(apiKey: String?)
  /** Drops the native session token for [sessionId], if any. */
  fun disposeSession(sessionId: String)
  suspend fun findPredictions(input: String, sessionId: String?, options: OptionsMsg): List<PredictionMsg>
  suspend fun fetchPlace(placeId: String, sessionId: String?, fields: List<String>, languageCode: String?, regionCode: String?): PlaceMsg
  suspend fun fetchPhoto(ref: PhotoRefMsg, maxWidth: Long?, maxHeight: Long?): PhotoDataMsg

  companion object {
    /** The codec used by PlacesHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `PlacesHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: PlacesHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.fl_place_autocomplete_platform_interface.PlacesHostApi.initialize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val apiKeyArg = args[0] as String?
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.initialize(apiKeyArg)
                listOf(null)
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.fl_place_autocomplete_platform_interface.PlacesHostApi.disposeSession$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.disposeSession(sessionIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.fl_place_autocomplete_platform_interface.PlacesHostApi.findPredictions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val inputArg = args[0] as String
            val sessionIdArg = args[1] as String?
            val optionsArg = args[2] as OptionsMsg
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.findPredictions(inputArg, sessionIdArg, optionsArg))
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.fl_place_autocomplete_platform_interface.PlacesHostApi.fetchPlace$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val placeIdArg = args[0] as String
            val sessionIdArg = args[1] as String?
            val fieldsArg = args[2] as List<String>
            val languageCodeArg = args[3] as String?
            val regionCodeArg = args[4] as String?
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.fetchPlace(placeIdArg, sessionIdArg, fieldsArg, languageCodeArg, regionCodeArg))
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.fl_place_autocomplete_platform_interface.PlacesHostApi.fetchPhoto$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val refArg = args[0] as PhotoRefMsg
            val maxWidthArg = args[1] as Long?
            val maxHeightArg = args[2] as Long?
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.fetchPhoto(refArg, maxWidthArg, maxHeightArg))
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
