name: fl_place_autocomplete_workspace
publish_to: none
environment:
  sdk: ^3.13.0
workspace:
  - fl_place_autocomplete
  - fl_place_autocomplete_platform_interface
  - fl_place_autocomplete_android
  - fl_place_autocomplete_ios
  - fl_place_autocomplete_web
