// Autogenerated from Pigeon (v29.0.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>"))"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Generated class from Pigeon that represents data sent in messages.
struct LatLngMsg: Hashable, CustomStringConvertible {
  var latitude: Double
  var longitude: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LatLngMsg? {
    let latitude = pigeonVar_list[0] as! Double
    let longitude = pigeonVar_list[1] as! Double

    return LatLngMsg(
      latitude: latitude,
      longitude: longitude
    )
  }
  func toList() -> [Any?] {
    return [
      latitude,
      longitude,
    ]
  }
  static func == (lhs: LatLngMsg, rhs: LatLngMsg) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.latitude, rhs.latitude) && MessagesPigeonInternal.deepEquals(lhs.longitude, rhs.longitude)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("LatLngMsg")
    MessagesPigeonInternal.deepHash(value: latitude, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: longitude, hasher: &hasher)
  }

  public var description: String {
    return "LatLngMsg(latitude: \(String(describing: latitude)), longitude: \(String(describing: longitude)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct LatLngBoundsMsg: Hashable, CustomStringConvertible {
  var southwest: LatLngMsg
  var northeast: LatLngMsg


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LatLngBoundsMsg? {
    let southwest = pigeonVar_list[0] as! LatLngMsg
    let northeast = pigeonVar_list[1] as! LatLngMsg

    return LatLngBoundsMsg(
      southwest: southwest,
      northeast: northeast
    )
  }
  func toList() -> [Any?] {
    return [
      southwest,
      northeast,
    ]
  }
  static func == (lhs: LatLngBoundsMsg, rhs: LatLngBoundsMsg) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.southwest, rhs.southwest) && MessagesPigeonInternal.deepEquals(lhs.northeast, rhs.northeast)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("LatLngBoundsMsg")
    MessagesPigeonInternal.deepHash(value: southwest, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: northeast, hasher: &hasher)
  }

  public var description: String {
    return "LatLngBoundsMsg(southwest: \(String(describing: southwest)), northeast: \(String(describing: northeast)))"
  }
}

/// Circle when [center] != null, rectangle when [bounds] != null.
///
/// Generated class from Pigeon that represents data sent in messages.
struct AreaMsg: Hashable, CustomStringConvertible {
  var center: LatLngMsg? = nil
  var radiusMeters: Double? = nil
  var bounds: LatLngBoundsMsg? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AreaMsg? {
    let center: LatLngMsg? = nilOrValue(pigeonVar_list[0])
    let radiusMeters: Double? = nilOrValue(pigeonVar_list[1])
    let bounds: LatLngBoundsMsg? = nilOrValue(pigeonVar_list[2])

    return AreaMsg(
      center: center,
      radiusMeters: radiusMeters,
      bounds: bounds
    )
  }
  func toList() -> [Any?] {
    return [
      center,
      radiusMeters,
      bounds,
    ]
  }
  static func == (lhs: AreaMsg, rhs: AreaMsg) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.center, rhs.center) && MessagesPigeonInternal.deepEquals(lhs.radiusMeters, rhs.radiusMeters) && MessagesPigeonInternal.deepEquals(lhs.bounds, rhs.bounds)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AreaMsg")
    MessagesPigeonInternal.deepHash(value: center, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: radiusMeters, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: bounds, hasher: &hasher)
  }

  public var description: String {
    return "AreaMsg(center: \(String(describing: center)), radiusMeters: \(String(describing: radiusMeters)), bounds: \(String(describing: bounds)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct OptionsMsg: Hashable, CustomStringConvertible {
  var locationBias: AreaMsg? = nil
  var locationRestriction: LatLngBoundsMsg? = nil
  var origin: LatLngMsg? = nil
  var includedPrimaryTypes: [String]
  var includedRegionCodes: [String]
  var languageCode: String? = nil
  var regionCode: String? = nil
  var inputOffset: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> OptionsMsg? {
    let locationBias: AreaMsg? = nilOrValue(pigeonVar_list[0])
    let locationRestriction: LatLngBoundsMsg? = nilOrValue(pigeonVar_list[1])
    let origin: LatLngMsg? = nilOrValue(pigeonVar_list[2])
    let includedPrimaryTypes = pigeonVar_list[3] as! [String]
    let includedRegionCodes = pigeonVar_list[4] as! [String]
    let languageCode: String? = nilOrValue(pigeonVar_list[5])
    let regionCode: String? = nilOrValue(pigeonVar_list[6])
    let inputOffset: Int64? = nilOrValue(pigeonVar_list[7])

    return OptionsMsg(
      locationBias: locationBias,
      locationRestriction: locationRestriction,
      origin: origin,
      includedPrimaryTypes: includedPrimaryTypes,
      includedRegionCodes: includedRegionCodes,
      languageCode: languageCode,
      regionCode: regionCode,
      inputOffset: inputOffset
    )
  }
  func toList() -> [Any?] {
    return [
      locationBias,
      locationRestriction,
      origin,
      includedPrimaryTypes,
      includedRegionCodes,
      languageCode,
      regionCode,
      inputOffset,
    ]
  }
  static func == (lhs: OptionsMsg, rhs: OptionsMsg) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.locationBias, rhs.locationBias) && MessagesPigeonInternal.deepEquals(lhs.locationRestriction, rhs.locationRestriction) && MessagesPigeonInternal.deepEquals(lhs.origin, rhs.origin) && MessagesPigeonInternal.deepEquals(lhs.includedPrimaryTypes, rhs.includedPrimaryTypes) && MessagesPigeonInternal.deepEquals(lhs.includedRegionCodes, rhs.includedRegionCodes) && MessagesPigeonInternal.deepEquals(lhs.languageCode, rhs.languageCode) && MessagesPigeonInternal.deepEquals(lhs.regionCode, rhs.regionCode) && MessagesPigeonInternal.deepEquals(lhs.inputOffset, rhs.inputOffset)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("OptionsMsg")
    MessagesPigeonInternal.deepHash(value: locationBias, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: locationRestriction, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: origin, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: includedPrimaryTypes, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: includedRegionCodes, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: languageCode, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: regionCode, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: inputOffset, hasher: &hasher)
  }

  public var description: String {
    return "OptionsMsg(locationBias: \(String(describing: locationBias)), locationRestriction: \(String(describing: locationRestriction)), origin: \(String(describing: origin)), includedPrimaryTypes: \(String(describing: includedPrimaryTypes)), includedRegionCodes: \(String(describing: includedRegionCodes)), languageCode: \(String(describing: languageCode)), regionCode: \(String(describing: regionCode)), inputOffset: \(String(describing: inputOffset)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct MatchedRangeMsg: Hashable, CustomStringConvertible {
  var start: Int64
  var end: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MatchedRangeMsg? {
    let start = pigeonVar_list[0] as! Int64
    let end = pigeonVar_list[1] as! Int64

    return MatchedRangeMsg(
      start: start,
      end: end
    )
  }
  func toList() -> [Any?] {
    return [
      start,
      end,
    ]
  }
  static func == (lhs: MatchedRangeMsg, rhs: MatchedRangeMsg) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.start, rhs.start) && MessagesPigeonInternal.deepEquals(lhs.end, rhs.end)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("MatchedRangeMsg")
    MessagesPigeonInternal.deepHash(value: start, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: end, hasher: &hasher)
  }

  public var description: String {
    return "MatchedRangeMsg(start: \(String(describing: start)), end: \(String(describing: end)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PredictionMsg: Hashable, CustomStringConvertible {
  var placeId: String
  var fullText: String
  var primaryText: String
  var secondaryText: String
  var matchedRanges: [MatchedRangeMsg]
  var types: [String]
  var distanceMeters: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PredictionMsg? {
    let placeId = pigeonVar_list[0] as! String
    let fullText = pigeonVar_list[1] as! String
    let primaryText = pigeonVar_list[2] as! String
    let secondaryText = pigeonVar_list[3] as! String
    let matchedRanges = pigeonVar_list[4] as! [MatchedRangeMsg]
    let types = pigeonVar_list[5] as! [String]
    let distanceMeters: Int64? = nilOrValue(pigeonVar_list[6])

    return PredictionMsg(
      placeId: placeId,
      fullText: fullText,
      primaryText: primaryText,
      secondaryText: secondaryText,
      matchedRanges: matchedRanges,
      types: types,
      distanceMeters: distanceMeters
    )
  }
  func toList() -> [Any?] {
    return [
      placeId,
      fullText,
      primaryText,
      secondaryText,
      matchedRanges,
      types,
      distanceMeters,
    ]
  }
  static func == (lhs: PredictionMsg, rhs: PredictionMsg) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.placeId, rhs.placeId) && MessagesPigeonInternal.deepEquals(lhs.fullText, rhs.fullText) && MessagesPigeonInternal.deepEquals(lhs.primaryText, rhs.primaryText) && MessagesPigeonInternal.deepEquals(lhs.secondaryText, rhs.secondaryText) && MessagesPigeonInternal.deepEquals(lhs.matchedRanges, rhs.matchedRanges) && MessagesPigeonInternal.deepEquals(lhs.types, rhs.types) && MessagesPigeonInternal.deepEquals(lhs.distanceMeters, rhs.distanceMeters)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PredictionMsg")
    MessagesPigeonInternal.deepHash(value: placeId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: fullText, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: primaryText, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: secondaryText, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: matchedRanges, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: types, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: distanceMeters, hasher: &hasher)
  }

  public var description: String {
    return "PredictionMsg(placeId: \(String(describing: placeId)), fullText: \(String(describing: fullText)), primaryText: \(String(describing: primaryText)), secondaryText: \(String(describing: secondaryText)), matchedRanges: \(String(describing: matchedRanges)), types: \(String(describing: types)), distanceMeters: \(String(describing: distanceMeters)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct AddressComponentMsg: Hashable, CustomStringConvertible {
  var longText: String? = nil
  var shortText: String? = nil
  var types: [String]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AddressComponentMsg? {
    let longText: String? = nilOrValue(pigeonVar_list[0])
    let shortText: String? = nilOrValue(pigeonVar_list[1])
    let types = pigeonVar_list[2] as! [String]

    return AddressComponentMsg(
      longText: longText,
      shortText: shortText,
      types: types
    )
  }
  func toList() -> [Any?] {
    return [
      longText,
      shortText,
      types,
    ]
  }
  static func == (lhs: AddressComponentMsg, rhs: AddressComponentMsg) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.longText, rhs.longText) && MessagesPigeonInternal.deepEquals(lhs.shortText, rhs.shortText) && MessagesPigeonInternal.deepEquals(lhs.types, rhs.types)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AddressComponentMsg")
    MessagesPigeonInternal.deepHash(value: longText, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: shortText, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: types, hasher: &hasher)
  }

  public var description: String {
    return "AddressComponentMsg(longText: \(String(describing: longText)), shortText: \(String(describing: shortText)), types: \(String(describing: types)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct TimePointMsg: Hashable, CustomStringConvertible {
  var day: Int64
  var hour: Int64
  var minute: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> TimePointMsg? {
    let day = pigeonVar_list[0] as! Int64
    let hour = pigeonVar_list[1] as! Int64
    let minute = pigeonVar_list[2] as! Int64

    return TimePointMsg(
      day: day,
      hour: hour,
      minute: minute
    )
  }
  func toList() -> [Any?] {
    return [
      day,
      hour,
      minute,
    ]
  }
  static func == (lhs: TimePointMsg, rhs: TimePointMsg) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.day, rhs.day) && MessagesPigeonInternal.deepEquals(lhs.hour, rhs.hour) && MessagesPigeonInternal.deepEquals(lhs.minute, rhs.minute)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("TimePointMsg")
    MessagesPigeonInternal.deepHash(value: day, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: hour, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: minute, hasher: &hasher)
  }

  public var description: String {
    return "TimePointMsg(day: \(String(describing: day)), hour: \(String(describing: hour)), minute: \(String(describing: minute)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct OpeningPeriodMsg: Hashable, CustomStringConvertible {
  var open: TimePointMsg? = nil
  var close: TimePointMsg? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> OpeningPeriodMsg? {
    let open: TimePointMsg? = nilOrValue(pigeonVar_list[0])
    let close: TimePointMsg? = nilOrValue(pigeonVar_list[1])

    return OpeningPeriodMsg(
      open: open,
      close: close
    )
  }
  func toList() -> [Any?] {
    return [
      open,
      close,
    ]
  }
  static func == (lhs: OpeningPeriodMsg, rhs: OpeningPeriodMsg) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.open, rhs.open) && MessagesPigeonInternal.deepEquals(lhs.close, rhs.close)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("OpeningPeriodMsg")
    MessagesPigeonInternal.deepHash(value: open, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: close, hasher: &hasher)
  }

  public var description: String {
    return "OpeningPeriodMsg(open: \(String(describing: open)), close: \(String(describing: close)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct OpeningHoursMsg: Hashable, CustomStringConvertible {
  var weekdayDescriptions: [String]
  var periods: [OpeningPeriodMsg]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> OpeningHoursMsg? {
    let weekdayDescriptions = pigeonVar_list[0] as! [String]
    let periods = pigeonVar_list[1] as! [OpeningPeriodMsg]

    return OpeningHoursMsg(
      weekdayDescriptions: weekdayDescriptions,
      periods: periods
    )
  }
  func toList() -> [Any?] {
    return [
      weekdayDescriptions,
      periods,
    ]
  }
  static func == (lhs: OpeningHoursMsg, rhs: OpeningHoursMsg) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.weekdayDescriptions, rhs.weekdayDescriptions) && MessagesPigeonInternal.deepEquals(lhs.periods, rhs.periods)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("OpeningHoursMsg")
    MessagesPigeonInternal.deepHash(value: weekdayDescriptions, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: periods, hasher: &hasher)
  }

  public var description: String {
    return "OpeningHoursMsg(weekdayDescriptions: \(String(describing: weekdayDescriptions)), periods: \(String(describing: periods)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct AuthorAttributionMsg: Hashable, CustomStringConvertible {
  var displayName: String? = nil
  var uri: String? = nil
  var photoUri: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AuthorAttributionMsg? {
    let displayName: String? = nilOrValue(pigeonVar_list[0])
    let uri: String? = nilOrValue(pigeonVar_list[1])
    let photoUri: String? = nilOrValue(pigeonVar_list[2])

    return AuthorAttributionMsg(
      displayName: displayName,
      uri: uri,
      photoUri: photoUri
    )
  }
  func toList() -> [Any?] {
    return [
      displayName,
      uri,
      photoUri,
    ]
  }
  static func == (lhs: AuthorAttributionMsg, rhs: AuthorAttributionMsg) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.displayName, rhs.displayName) && MessagesPigeonInternal.deepEquals(lhs.uri, rhs.uri) && MessagesPigeonInternal.deepEquals(lhs.photoUri, rhs.photoUri)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AuthorAttributionMsg")
    MessagesPigeonInternal.deepHash(value: displayName, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: uri, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: photoUri, hasher: &hasher)
  }

  public var description: String {
    return "AuthorAttributionMsg(displayName: \(String(describing: displayName)), uri: \(String(describing: uri)), photoUri: \(String(describing: photoUri)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PhotoRefMsg: Hashable, CustomStringConvertible {
  var id: String
  var widthPx: Int64? = nil
  var heightPx: Int64? = nil
  var authorAttributions: [AuthorAttributionMsg]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PhotoRefMsg? {
    let id = pigeonVar_list[0] as! String
    let widthPx: Int64? = nilOrValue(pigeonVar_list[1])
    let heightPx: Int64? = nilOrValue(pigeonVar_list[2])
    let authorAttributions = pigeonVar_list[3] as! [AuthorAttributionMsg]

    return PhotoRefMsg(
      id: id,
      widthPx: widthPx,
      heightPx: heightPx,
      authorAttributions: authorAttributions
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      widthPx,
      heightPx,
      authorAttributions,
    ]
  }
  static func == (lhs: PhotoRefMsg, rhs: PhotoRefMsg) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.id, rhs.id) && MessagesPigeonInternal.deepEquals(lhs.widthPx, rhs.widthPx) && MessagesPigeonInternal.deepEquals(lhs.heightPx, rhs.heightPx) && MessagesPigeonInternal.deepEquals(lhs.authorAttributions, rhs.authorAttributions)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PhotoRefMsg")
    MessagesPigeonInternal.deepHash(value: id, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: widthPx, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: heightPx, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: authorAttributions, hasher: &hasher)
  }

  public var description: String {
    return "PhotoRefMsg(id: \(String(describing: id)), widthPx: \(String(describing: widthPx)), heightPx: \(String(describing: heightPx)), authorAttributions: \(String(describing: authorAttributions)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ReviewMsg: Hashable, CustomStringConvertible {
  var authorAttribution: AuthorAttributionMsg? = nil
  var rating: Double? = nil
  var text: String? = nil
  var relativePublishTimeDescription: String? = nil
  var publishTime: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ReviewMsg? {
    let authorAttribution: AuthorAttributionMsg? = nilOrValue(pigeonVar_list[0])
    let rating: Double? = nilOrValue(pigeonVar_list[1])
    let text: String? = nilOrValue(pigeonVar_list[2])
    let relativePublishTimeDescription: String? = nilOrValue(pigeonVar_list[3])
    let publishTime: String? = nilOrValue(pigeonVar_list[4])

    return ReviewMsg(
      authorAttribution: authorAttribution,
      rating: rating,
      text: text,
      relativePublishTimeDescription: relativePublishTimeDescription,
      publishTime: publishTime
    )
  }
  func toList() -> [Any?] {
    return [
      authorAttribution,
      rating,
      text,
      relativePublishTimeDescription,
      publishTime,
    ]
  }
  static func == (lhs: ReviewMsg, rhs: ReviewMsg) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.authorAttribution, rhs.authorAttribution) && MessagesPigeonInternal.deepEquals(lhs.rating, rhs.rating) && MessagesPigeonInternal.deepEquals(lhs.text, rhs.text) && MessagesPigeonInternal.deepEquals(lhs.relativePublishTimeDescription, rhs.relativePublishTimeDescription) && MessagesPigeonInternal.deepEquals(lhs.publishTime, rhs.publishTime)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ReviewMsg")
    MessagesPigeonInternal.deepHash(value: authorAttribution, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: rating, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: text, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: relativePublishTimeDescription, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: publishTime, hasher: &hasher)
  }

  public var description: String {
    return "ReviewMsg(authorAttribution: \(String(describing: authorAttribution)), rating: \(String(describing: rating)), text: \(String(describing: text)), relativePublishTimeDescription: \(String(describing: relativePublishTimeDescription)), publishTime: \(String(describing: publishTime)))"
  }
}

/// All fields optional; only requested fields are populated.
/// priceLevel: free|inexpensive|moderate|expensive|veryExpensive.
/// businessStatus: operational|closedTemporarily|closedPermanently.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PlaceMsg: Hashable, CustomStringConvertible {
  var id: String? = nil
  var displayName: String? = nil
  var formattedAddress: String? = nil
  var shortFormattedAddress: String? = nil
  var location: LatLngMsg? = nil
  var viewport: LatLngBoundsMsg? = nil
  var addressComponents: [AddressComponentMsg]? = nil
  var types: [String]? = nil
  var primaryType: String? = nil
  var primaryTypeDisplayName: String? = nil
  var rating: Double? = nil
  var userRatingCount: Int64? = nil
  var priceLevel: String? = nil
  var nationalPhoneNumber: String? = nil
  var internationalPhoneNumber: String? = nil
  var websiteUri: String? = nil
  var googleMapsUri: String? = nil
  var utcOffsetMinutes: Int64? = nil
  var businessStatus: String? = nil
  var editorialSummary: String? = nil
  var regularOpeningHours: OpeningHoursMsg? = nil
  var photos: [PhotoRefMsg]? = nil
  var reviews: [ReviewMsg]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlaceMsg? {
    let id: String? = nilOrValue(pigeonVar_list[0])
    let displayName: String? = nilOrValue(pigeonVar_list[1])
    let formattedAddress: String? = nilOrValue(pigeonVar_list[2])
    let shortFormattedAddress: String? = nilOrValue(pigeonVar_list[3])
    let location: LatLngMsg? = nilOrValue(pigeonVar_list[4])
    let viewport: LatLngBoundsMsg? = nilOrValue(pigeonVar_list[5])
    let addressComponents: [AddressComponentMsg]? = nilOrValue(pigeonVar_list[6])
    let types: [String]? = nilOrValue(pigeonVar_list[7])
    let primaryType: String? = nilOrValue(pigeonVar_list[8])
    let primaryTypeDisplayName: String? = nilOrValue(pigeonVar_list[9])
    let rating: Double? = nilOrValue(pigeonVar_list[10])
    let userRatingCount: Int64? = nilOrValue(pigeonVar_list[11])
    let priceLevel: String? = nilOrValue(pigeonVar_list[12])
    let nationalPhoneNumber: String? = nilOrValue(pigeonVar_list[13])
    let internationalPhoneNumber: String? = nilOrValue(pigeonVar_list[14])
    let websiteUri: String? = nilOrValue(pigeonVar_list[15])
    let googleMapsUri: String? = nilOrValue(pigeonVar_list[16])
    let utcOffsetMinutes: Int64? = nilOrValue(pigeonVar_list[17])
    let businessStatus: String? = nilOrValue(pigeonVar_list[18])
    let editorialSummary: String? = nilOrValue(pigeonVar_list[19])
    let regularOpeningHours: OpeningHoursMsg? = nilOrValue(pigeonVar_list[20])
    let photos: [PhotoRefMsg]? = nilOrValue(pigeonVar_list[21])
    let reviews: [ReviewMsg]? = nilOrValue(pigeonVar_list[22])

    return PlaceMsg(
      id: id,
      displayName: displayName,
      formattedAddress: formattedAddress,
      shortFormattedAddress: shortFormattedAddress,
      location: location,
      viewport: viewport,
      addressComponents: addressComponents,
      types: types,
      primaryType: primaryType,
      primaryTypeDisplayName: primaryTypeDisplayName,
      rating: rating,
      userRatingCount: userRatingCount,
      priceLevel: priceLevel,
      nationalPhoneNumber: nationalPhoneNumber,
      internationalPhoneNumber: internationalPhoneNumber,
      websiteUri: websiteUri,
      googleMapsUri: googleMapsUri,
      utcOffsetMinutes: utcOffsetMinutes,
      businessStatus: businessStatus,
      editorialSummary: editorialSummary,
      regularOpeningHours: regularOpeningHours,
      photos: photos,
      reviews: reviews
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      displayName,
      formattedAddress,
      shortFormattedAddress,
      location,
      viewport,
      addressComponents,
      types,
      primaryType,
      primaryTypeDisplayName,
      rating,
      userRatingCount,
      priceLevel,
      nationalPhoneNumber,
      internationalPhoneNumber,
      websiteUri,
      googleMapsUri,
      utcOffsetMinutes,
      businessStatus,
      editorialSummary,
      regularOpeningHours,
      photos,
      reviews,
    ]
  }
  static func == (lhs: PlaceMsg, rhs: PlaceMsg) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.id, rhs.id) && MessagesPigeonInternal.deepEquals(lhs.displayName, rhs.displayName) && MessagesPigeonInternal.deepEquals(lhs.formattedAddress, rhs.formattedAddress) && MessagesPigeonInternal.deepEquals(lhs.shortFormattedAddress, rhs.shortFormattedAddress) && MessagesPigeonInternal.deepEquals(lhs.location, rhs.location) && MessagesPigeonInternal.deepEquals(lhs.viewport, rhs.viewport) && MessagesPigeonInternal.deepEquals(lhs.addressComponents, rhs.addressComponents) && MessagesPigeonInternal.deepEquals(lhs.types, rhs.types) && MessagesPigeonInternal.deepEquals(lhs.primaryType, rhs.primaryType) && MessagesPigeonInternal.deepEquals(lhs.primaryTypeDisplayName, rhs.primaryTypeDisplayName) && MessagesPigeonInternal.deepEquals(lhs.rating, rhs.rating) && MessagesPigeonInternal.deepEquals(lhs.userRatingCount, rhs.userRatingCount) && MessagesPigeonInternal.deepEquals(lhs.priceLevel, rhs.priceLevel) && MessagesPigeonInternal.deepEquals(lhs.nationalPhoneNumber, rhs.nationalPhoneNumber) && MessagesPigeonInternal.deepEquals(lhs.internationalPhoneNumber, rhs.internationalPhoneNumber) && MessagesPigeonInternal.deepEquals(lhs.websiteUri, rhs.websiteUri) && MessagesPigeonInternal.deepEquals(lhs.googleMapsUri, rhs.googleMapsUri) && MessagesPigeonInternal.deepEquals(lhs.utcOffsetMinutes, rhs.utcOffsetMinutes) && MessagesPigeonInternal.deepEquals(lhs.businessStatus, rhs.businessStatus) && MessagesPigeonInternal.deepEquals(lhs.editorialSummary, rhs.editorialSummary) && MessagesPigeonInternal.deepEquals(lhs.regularOpeningHours, rhs.regularOpeningHours) && MessagesPigeonInternal.deepEquals(lhs.photos, rhs.photos) && MessagesPigeonInternal.deepEquals(lhs.reviews, rhs.reviews)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PlaceMsg")
    MessagesPigeonInternal.deepHash(value: id, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: displayName, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: formattedAddress, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: shortFormattedAddress, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: location, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: viewport, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: addressComponents, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: types, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: primaryType, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: primaryTypeDisplayName, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: rating, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: userRatingCount, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: priceLevel, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: nationalPhoneNumber, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: internationalPhoneNumber, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: websiteUri, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: googleMapsUri, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: utcOffsetMinutes, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: businessStatus, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: editorialSummary, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: regularOpeningHours, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: photos, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: reviews, hasher: &hasher)
  }

  public var description: String {
    return "PlaceMsg(id: \(String(describing: id)), displayName: \(String(describing: displayName)), formattedAddress: \(String(describing: formattedAddress)), shortFormattedAddress: \(String(describing: shortFormattedAddress)), location: \(String(describing: location)), viewport: \(String(describing: viewport)), addressComponents: \(String(describing: addressComponents)), types: \(String(describing: types)), primaryType: \(String(describing: primaryType)), primaryTypeDisplayName: \(String(describing: primaryTypeDisplayName)), rating: \(String(describing: rating)), userRatingCount: \(String(describing: userRatingCount)), priceLevel: \(String(describing: priceLevel)), nationalPhoneNumber: \(String(describing: nationalPhoneNumber)), internationalPhoneNumber: \(String(describing: internationalPhoneNumber)), websiteUri: \(String(describing: websiteUri)), googleMapsUri: \(String(describing: googleMapsUri)), utcOffsetMinutes: \(String(describing: utcOffsetMinutes)), businessStatus: \(String(describing: businessStatus)), editorialSummary: \(String(describing: editorialSummary)), regularOpeningHours: \(String(describing: regularOpeningHours)), photos: \(String(describing: photos)), reviews: \(String(describing: reviews)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PhotoDataMsg: Hashable, CustomStringConvertible {
  var bytes: FlutterStandardTypedData? = nil
  var uri: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PhotoDataMsg? {
    let bytes: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[0])
    let uri: String? = nilOrValue(pigeonVar_list[1])

    return PhotoDataMsg(
      bytes: bytes,
      uri: uri
    )
  }
  func toList() -> [Any?] {
    return [
      bytes,
      uri,
    ]
  }
  static func == (lhs: PhotoDataMsg, rhs: PhotoDataMsg) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.bytes, rhs.bytes) && MessagesPigeonInternal.deepEquals(lhs.uri, rhs.uri)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PhotoDataMsg")
    MessagesPigeonInternal.deepHash(value: bytes, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: uri, hasher: &hasher)
  }

  public var description: String {
    return "PhotoDataMsg(bytes: \(String(describing: bytes)), uri: \(String(describing: uri)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return LatLngMsg.fromList(self.readValue() as! [Any?])
    case 130:
      return LatLngBoundsMsg.fromList(self.readValue() as! [Any?])
    case 131:
      return AreaMsg.fromList(self.readValue() as! [Any?])
    case 132:
      return OptionsMsg.fromList(self.readValue() as! [Any?])
    case 133:
      return MatchedRangeMsg.fromList(self.readValue() as! [Any?])
    case 134:
      return PredictionMsg.fromList(self.readValue() as! [Any?])
    case 135:
      return AddressComponentMsg.fromList(self.readValue() as! [Any?])
    case 136:
      return TimePointMsg.fromList(self.readValue() as! [Any?])
    case 137:
      return OpeningPeriodMsg.fromList(self.readValue() as! [Any?])
    case 138:
      return OpeningHoursMsg.fromList(self.readValue() as! [Any?])
    case 139:
      return AuthorAttributionMsg.fromList(self.readValue() as! [Any?])
    case 140:
      return PhotoRefMsg.fromList(self.readValue() as! [Any?])
    case 141:
      return ReviewMsg.fromList(self.readValue() as! [Any?])
    case 142:
      return PlaceMsg.fromList(self.readValue() as! [Any?])
    case 143:
      return PhotoDataMsg.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? LatLngMsg {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? LatLngBoundsMsg {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? AreaMsg {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? OptionsMsg {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? MatchedRangeMsg {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? PredictionMsg {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? AddressComponentMsg {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? TimePointMsg {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? OpeningPeriodMsg {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? OpeningHoursMsg {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? AuthorAttributionMsg {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else if let value = value as? PhotoRefMsg {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else if let value = value as? ReviewMsg {
      super.writeByte(141)
      super.writeValue(value.toList())
    } else if let value = value as? PlaceMsg {
      super.writeByte(142)
      super.writeValue(value.toList())
    } else if let value = value as? PhotoDataMsg {
      super.writeByte(143)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol PlacesHostApi {
  /// Initializes the native SDK once, before the first Places call.
  ///
  /// [apiKey] is the key resolved from `--dart-define` (null when none was
  /// given); a null/blank value falls back to the native configuration
  /// (AndroidManifest meta-data / Info.plist). Throws
  /// FlutterError(invalidApiKey) when no key is found anywhere.
  func initialize(apiKey: String?) async throws
  /// Drops the native session token for [sessionId], if any.
  func disposeSession(sessionId: String) throws
  func findPredictions(input: String, sessionId: String?, options: OptionsMsg) async throws -> [PredictionMsg]
  func fetchPlace(placeId: String, sessionId: String?, fields: [String], languageCode: String?, regionCode: String?) async throws -> PlaceMsg
  func fetchPhoto(ref: PhotoRefMsg, maxWidth: Int64?, maxHeight: Int64?) async throws -> PhotoDataMsg
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class PlacesHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `PlacesHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: PlacesHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Initializes the native SDK once, before the first Places call.
    ///
    /// [apiKey] is the key resolved from `--dart-define` (null when none was
    /// given); a null/blank value falls back to the native configuration
    /// (AndroidManifest meta-data / Info.plist). Throws
    /// FlutterError(invalidApiKey) when no key is found anywhere.
    let initializeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.fl_place_autocomplete_platform_interface.PlacesHostApi.initialize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let apiKeyArg: String? = nilOrValue(args[0])
        Task { @MainActor in
          do {
            try await api.initialize(apiKey: apiKeyArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
    /// Drops the native session token for [sessionId], if any.
    let disposeSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.fl_place_autocomplete_platform_interface.PlacesHostApi.disposeSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disposeSessionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! String
        do {
          try api.disposeSession(sessionId: sessionIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      disposeSessionChannel.setMessageHandler(nil)
    }
    let findPredictionsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.fl_place_autocomplete_platform_interface.PlacesHostApi.findPredictions\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      findPredictionsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let inputArg = args[0] as! String
        let sessionIdArg: String? = nilOrValue(args[1])
        let optionsArg = args[2] as! OptionsMsg
        Task { @MainActor in
          do {
            let result = try await api.findPredictions(input: inputArg, sessionId: sessionIdArg, options: optionsArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      findPredictionsChannel.setMessageHandler(nil)
    }
    let fetchPlaceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.fl_place_autocomplete_platform_interface.PlacesHostApi.fetchPlace\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      fetchPlaceChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let placeIdArg = args[0] as! String
        let sessionIdArg: String? = nilOrValue(args[1])
        let fieldsArg = args[2] as! [String]
        let languageCodeArg: String? = nilOrValue(args[3])
        let regionCodeArg: String? = nilOrValue(args[4])
        Task { @MainActor in
          do {
            let result = try await api.fetchPlace(placeId: placeIdArg, sessionId: sessionIdArg, fields: fieldsArg, languageCode: languageCodeArg, regionCode: regionCodeArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      fetchPlaceChannel.setMessageHandler(nil)
    }
    let fetchPhotoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.fl_place_autocomplete_platform_interface.PlacesHostApi.fetchPhoto\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      fetchPhotoChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let refArg = args[0] as! PhotoRefMsg
        let maxWidthArg: Int64? = nilOrValue(args[1])
        let maxHeightArg: Int64? = nilOrValue(args[2])
        Task { @MainActor in
          do {
            let result = try await api.fetchPhoto(ref: refArg, maxWidth: maxWidthArg, maxHeight: maxHeightArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      fetchPhotoChannel.setMessageHandler(nil)
    }
  }
}
