name: fl_place_autocomplete_web
description: "Web implementation of fl_place_autocomplete."
version: 0.1.0
repository: https://github.com/mk7/fl_place_autocomplete

environment:
  sdk: ^3.13.0
  flutter: ">=3.44.0"
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.1.0
  fl_place_autocomplete_platform_interface: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    implements: fl_place_autocomplete
    platforms:
      web:
        pluginClass: FlPlaceAutocompleteWeb
        fileName: fl_place_autocomplete_web.dart
