// Autogenerated from Pigeon (v29.0.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


class LatLngMsg {
  LatLngMsg({
    required this.latitude,
    required this.longitude,
  });

  double latitude;

  double longitude;

  List<Object?> _toList() {
    return <Object?>[
      latitude,
      longitude,
    ];
  }

  Object encode() {
    return _toList();  }

  static LatLngMsg decode(Object result) {
    result as List<Object?>;
    return LatLngMsg(
      latitude: result[0]! as double,
      longitude: result[1]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! LatLngMsg || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(latitude, other.latitude) && _deepEquals(longitude, other.longitude);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'LatLngMsg(latitude: $latitude, longitude: $longitude)';
  }
}

class LatLngBoundsMsg {
  LatLngBoundsMsg({
    required this.southwest,
    required this.northeast,
  });

  LatLngMsg southwest;

  LatLngMsg northeast;

  List<Object?> _toList() {
    return <Object?>[
      southwest,
      northeast,
    ];
  }

  Object encode() {
    return _toList();  }

  static LatLngBoundsMsg decode(Object result) {
    result as List<Object?>;
    return LatLngBoundsMsg(
      southwest: result[0]! as LatLngMsg,
      northeast: result[1]! as LatLngMsg,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! LatLngBoundsMsg || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(southwest, other.southwest) && _deepEquals(northeast, other.northeast);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'LatLngBoundsMsg(southwest: $southwest, northeast: $northeast)';
  }
}

/// Circle when [center] != null, rectangle when [bounds] != null.
class AreaMsg {
  AreaMsg({
    this.center,
    this.radiusMeters,
    this.bounds,
  });

  LatLngMsg? center;

  double? radiusMeters;

  LatLngBoundsMsg? bounds;

  List<Object?> _toList() {
    return <Object?>[
      center,
      radiusMeters,
      bounds,
    ];
  }

  Object encode() {
    return _toList();  }

  static AreaMsg decode(Object result) {
    result as List<Object?>;
    return AreaMsg(
      center: result[0] as LatLngMsg?,
      radiusMeters: result[1] as double?,
      bounds: result[2] as LatLngBoundsMsg?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AreaMsg || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(center, other.center) && _deepEquals(radiusMeters, other.radiusMeters) && _deepEquals(bounds, other.bounds);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AreaMsg(center: $center, radiusMeters: $radiusMeters, bounds: $bounds)';
  }
}

class OptionsMsg {
  OptionsMsg({
    this.locationBias,
    this.locationRestriction,
    this.origin,
    required this.includedPrimaryTypes,
    required this.includedRegionCodes,
    this.languageCode,
    this.regionCode,
    this.inputOffset,
  });

  AreaMsg? locationBias;

  LatLngBoundsMsg? locationRestriction;

  LatLngMsg? origin;

  List<String> includedPrimaryTypes;

  List<String> includedRegionCodes;

  String? languageCode;

  String? regionCode;

  int? inputOffset;

  List<Object?> _toList() {
    return <Object?>[
      locationBias,
      locationRestriction,
      origin,
      includedPrimaryTypes,
      includedRegionCodes,
      languageCode,
      regionCode,
      inputOffset,
    ];
  }

  Object encode() {
    return _toList();  }

  static OptionsMsg decode(Object result) {
    result as List<Object?>;
    return OptionsMsg(
      locationBias: result[0] as AreaMsg?,
      locationRestriction: result[1] as LatLngBoundsMsg?,
      origin: result[2] as LatLngMsg?,
      includedPrimaryTypes: (result[3]! as List<Object?>).cast<String>(),
      includedRegionCodes: (result[4]! as List<Object?>).cast<String>(),
      languageCode: result[5] as String?,
      regionCode: result[6] as String?,
      inputOffset: result[7] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! OptionsMsg || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(locationBias, other.locationBias) && _deepEquals(locationRestriction, other.locationRestriction) && _deepEquals(origin, other.origin) && _deepEquals(includedPrimaryTypes, other.includedPrimaryTypes) && _deepEquals(includedRegionCodes, other.includedRegionCodes) && _deepEquals(languageCode, other.languageCode) && _deepEquals(regionCode, other.regionCode) && _deepEquals(inputOffset, other.inputOffset);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'OptionsMsg(locationBias: $locationBias, locationRestriction: $locationRestriction, origin: $origin, includedPrimaryTypes: $includedPrimaryTypes, includedRegionCodes: $includedRegionCodes, languageCode: $languageCode, regionCode: $regionCode, inputOffset: $inputOffset)';
  }
}

class MatchedRangeMsg {
  MatchedRangeMsg({
    required this.start,
    required this.end,
  });

  int start;

  int end;

  List<Object?> _toList() {
    return <Object?>[
      start,
      end,
    ];
  }

  Object encode() {
    return _toList();  }

  static MatchedRangeMsg decode(Object result) {
    result as List<Object?>;
    return MatchedRangeMsg(
      start: result[0]! as int,
      end: result[1]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MatchedRangeMsg || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(start, other.start) && _deepEquals(end, other.end);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'MatchedRangeMsg(start: $start, end: $end)';
  }
}

class PredictionMsg {
  PredictionMsg({
    required this.placeId,
    required this.fullText,
    required this.primaryText,
    required this.secondaryText,
    required this.matchedRanges,
    required this.types,
    this.distanceMeters,
  });

  String placeId;

  String fullText;

  String primaryText;

  String secondaryText;

  List<MatchedRangeMsg> matchedRanges;

  List<String> types;

  int? distanceMeters;

  List<Object?> _toList() {
    return <Object?>[
      placeId,
      fullText,
      primaryText,
      secondaryText,
      matchedRanges,
      types,
      distanceMeters,
    ];
  }

  Object encode() {
    return _toList();  }

  static PredictionMsg decode(Object result) {
    result as List<Object?>;
    return PredictionMsg(
      placeId: result[0]! as String,
      fullText: result[1]! as String,
      primaryText: result[2]! as String,
      secondaryText: result[3]! as String,
      matchedRanges: (result[4]! as List<Object?>).cast<MatchedRangeMsg>(),
      types: (result[5]! as List<Object?>).cast<String>(),
      distanceMeters: result[6] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PredictionMsg || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(placeId, other.placeId) && _deepEquals(fullText, other.fullText) && _deepEquals(primaryText, other.primaryText) && _deepEquals(secondaryText, other.secondaryText) && _deepEquals(matchedRanges, other.matchedRanges) && _deepEquals(types, other.types) && _deepEquals(distanceMeters, other.distanceMeters);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PredictionMsg(placeId: $placeId, fullText: $fullText, primaryText: $primaryText, secondaryText: $secondaryText, matchedRanges: $matchedRanges, types: $types, distanceMeters: $distanceMeters)';
  }
}

class AddressComponentMsg {
  AddressComponentMsg({
    this.longText,
    this.shortText,
    required this.types,
  });

  String? longText;

  String? shortText;

  List<String> types;

  List<Object?> _toList() {
    return <Object?>[
      longText,
      shortText,
      types,
    ];
  }

  Object encode() {
    return _toList();  }

  static AddressComponentMsg decode(Object result) {
    result as List<Object?>;
    return AddressComponentMsg(
      longText: result[0] as String?,
      shortText: result[1] as String?,
      types: (result[2]! as List<Object?>).cast<String>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AddressComponentMsg || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(longText, other.longText) && _deepEquals(shortText, other.shortText) && _deepEquals(types, other.types);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AddressComponentMsg(longText: $longText, shortText: $shortText, types: $types)';
  }
}

class TimePointMsg {
  TimePointMsg({
    required this.day,
    required this.hour,
    required this.minute,
  });

  int day;

  int hour;

  int minute;

  List<Object?> _toList() {
    return <Object?>[
      day,
      hour,
      minute,
    ];
  }

  Object encode() {
    return _toList();  }

  static TimePointMsg decode(Object result) {
    result as List<Object?>;
    return TimePointMsg(
      day: result[0]! as int,
      hour: result[1]! as int,
      minute: result[2]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! TimePointMsg || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(day, other.day) && _deepEquals(hour, other.hour) && _deepEquals(minute, other.minute);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'TimePointMsg(day: $day, hour: $hour, minute: $minute)';
  }
}

class OpeningPeriodMsg {
  OpeningPeriodMsg({
    this.open,
    this.close,
  });

  TimePointMsg? open;

  TimePointMsg? close;

  List<Object?> _toList() {
    return <Object?>[
      open,
      close,
    ];
  }

  Object encode() {
    return _toList();  }

  static OpeningPeriodMsg decode(Object result) {
    result as List<Object?>;
    return OpeningPeriodMsg(
      open: result[0] as TimePointMsg?,
      close: result[1] as TimePointMsg?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! OpeningPeriodMsg || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(open, other.open) && _deepEquals(close, other.close);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'OpeningPeriodMsg(open: $open, close: $close)';
  }
}

class OpeningHoursMsg {
  OpeningHoursMsg({
    required this.weekdayDescriptions,
    required this.periods,
  });

  List<String> weekdayDescriptions;

  List<OpeningPeriodMsg> periods;

  List<Object?> _toList() {
    return <Object?>[
      weekdayDescriptions,
      periods,
    ];
  }

  Object encode() {
    return _toList();  }

  static OpeningHoursMsg decode(Object result) {
    result as List<Object?>;
    return OpeningHoursMsg(
      weekdayDescriptions: (result[0]! as List<Object?>).cast<String>(),
      periods: (result[1]! as List<Object?>).cast<OpeningPeriodMsg>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! OpeningHoursMsg || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(weekdayDescriptions, other.weekdayDescriptions) && _deepEquals(periods, other.periods);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'OpeningHoursMsg(weekdayDescriptions: $weekdayDescriptions, periods: $periods)';
  }
}

class AuthorAttributionMsg {
  AuthorAttributionMsg({
    this.displayName,
    this.uri,
    this.photoUri,
  });

  String? displayName;

  String? uri;

  String? photoUri;

  List<Object?> _toList() {
    return <Object?>[
      displayName,
      uri,
      photoUri,
    ];
  }

  Object encode() {
    return _toList();  }

  static AuthorAttributionMsg decode(Object result) {
    result as List<Object?>;
    return AuthorAttributionMsg(
      displayName: result[0] as String?,
      uri: result[1] as String?,
      photoUri: result[2] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AuthorAttributionMsg || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(displayName, other.displayName) && _deepEquals(uri, other.uri) && _deepEquals(photoUri, other.photoUri);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AuthorAttributionMsg(displayName: $displayName, uri: $uri, photoUri: $photoUri)';
  }
}

class PhotoRefMsg {
  PhotoRefMsg({
    required this.id,
    this.widthPx,
    this.heightPx,
    required this.authorAttributions,
  });

  String id;

  int? widthPx;

  int? heightPx;

  List<AuthorAttributionMsg> authorAttributions;

  List<Object?> _toList() {
    return <Object?>[
      id,
      widthPx,
      heightPx,
      authorAttributions,
    ];
  }

  Object encode() {
    return _toList();  }

  static PhotoRefMsg decode(Object result) {
    result as List<Object?>;
    return PhotoRefMsg(
      id: result[0]! as String,
      widthPx: result[1] as int?,
      heightPx: result[2] as int?,
      authorAttributions: (result[3]! as List<Object?>).cast<AuthorAttributionMsg>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PhotoRefMsg || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) && _deepEquals(widthPx, other.widthPx) && _deepEquals(heightPx, other.heightPx) && _deepEquals(authorAttributions, other.authorAttributions);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PhotoRefMsg(id: $id, widthPx: $widthPx, heightPx: $heightPx, authorAttributions: $authorAttributions)';
  }
}

class ReviewMsg {
  ReviewMsg({
    this.authorAttribution,
    this.rating,
    this.text,
    this.relativePublishTimeDescription,
    this.publishTime,
  });

  AuthorAttributionMsg? authorAttribution;

  double? rating;

  String? text;

  String? relativePublishTimeDescription;

  String? publishTime;

  List<Object?> _toList() {
    return <Object?>[
      authorAttribution,
      rating,
      text,
      relativePublishTimeDescription,
      publishTime,
    ];
  }

  Object encode() {
    return _toList();  }

  static ReviewMsg decode(Object result) {
    result as List<Object?>;
    return ReviewMsg(
      authorAttribution: result[0] as AuthorAttributionMsg?,
      rating: result[1] as double?,
      text: result[2] as String?,
      relativePublishTimeDescription: result[3] as String?,
      publishTime: result[4] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ReviewMsg || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(authorAttribution, other.authorAttribution) && _deepEquals(rating, other.rating) && _deepEquals(text, other.text) && _deepEquals(relativePublishTimeDescription, other.relativePublishTimeDescription) && _deepEquals(publishTime, other.publishTime);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ReviewMsg(authorAttribution: $authorAttribution, rating: $rating, text: $text, relativePublishTimeDescription: $relativePublishTimeDescription, publishTime: $publishTime)';
  }
}

/// All fields optional; only requested fields are populated.
/// priceLevel: free|inexpensive|moderate|expensive|veryExpensive.
/// businessStatus: operational|closedTemporarily|closedPermanently.
class PlaceMsg {
  PlaceMsg({
    this.id,
    this.displayName,
    this.formattedAddress,
    this.shortFormattedAddress,
    this.location,
    this.viewport,
    this.addressComponents,
    this.types,
    this.primaryType,
    this.primaryTypeDisplayName,
    this.rating,
    this.userRatingCount,
    this.priceLevel,
    this.nationalPhoneNumber,
    this.internationalPhoneNumber,
    this.websiteUri,
    this.googleMapsUri,
    this.utcOffsetMinutes,
    this.businessStatus,
    this.editorialSummary,
    this.regularOpeningHours,
    this.photos,
    this.reviews,
  });

  String? id;

  String? displayName;

  String? formattedAddress;

  String? shortFormattedAddress;

  LatLngMsg? location;

  LatLngBoundsMsg? viewport;

  List<AddressComponentMsg>? addressComponents;

  List<String>? types;

  String? primaryType;

  String? primaryTypeDisplayName;

  double? rating;

  int? userRatingCount;

  String? priceLevel;

  String? nationalPhoneNumber;

  String? internationalPhoneNumber;

  String? websiteUri;

  String? googleMapsUri;

  int? utcOffsetMinutes;

  String? businessStatus;

  String? editorialSummary;

  OpeningHoursMsg? regularOpeningHours;

  List<PhotoRefMsg>? photos;

  List<ReviewMsg>? reviews;

  List<Object?> _toList() {
    return <Object?>[
      id,
      displayName,
      formattedAddress,
      shortFormattedAddress,
      location,
      viewport,
      addressComponents,
      types,
      primaryType,
      primaryTypeDisplayName,
      rating,
      userRatingCount,
      priceLevel,
      nationalPhoneNumber,
      internationalPhoneNumber,
      websiteUri,
      googleMapsUri,
      utcOffsetMinutes,
      businessStatus,
      editorialSummary,
      regularOpeningHours,
      photos,
      reviews,
    ];
  }

  Object encode() {
    return _toList();  }

  static PlaceMsg decode(Object result) {
    result as List<Object?>;
    return PlaceMsg(
      id: result[0] as String?,
      displayName: result[1] as String?,
      formattedAddress: result[2] as String?,
      shortFormattedAddress: result[3] as String?,
      location: result[4] as LatLngMsg?,
      viewport: result[5] as LatLngBoundsMsg?,
      addressComponents: (result[6] as List<Object?>?)?.cast<AddressComponentMsg>(),
      types: (result[7] as List<Object?>?)?.cast<String>(),
      primaryType: result[8] as String?,
      primaryTypeDisplayName: result[9] as String?,
      rating: result[10] as double?,
      userRatingCount: result[11] as int?,
      priceLevel: result[12] as String?,
      nationalPhoneNumber: result[13] as String?,
      internationalPhoneNumber: result[14] as String?,
      websiteUri: result[15] as String?,
      googleMapsUri: result[16] as String?,
      utcOffsetMinutes: result[17] as int?,
      businessStatus: result[18] as String?,
      editorialSummary: result[19] as String?,
      regularOpeningHours: result[20] as OpeningHoursMsg?,
      photos: (result[21] as List<Object?>?)?.cast<PhotoRefMsg>(),
      reviews: (result[22] as List<Object?>?)?.cast<ReviewMsg>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlaceMsg || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) && _deepEquals(displayName, other.displayName) && _deepEquals(formattedAddress, other.formattedAddress) && _deepEquals(shortFormattedAddress, other.shortFormattedAddress) && _deepEquals(location, other.location) && _deepEquals(viewport, other.viewport) && _deepEquals(addressComponents, other.addressComponents) && _deepEquals(types, other.types) && _deepEquals(primaryType, other.primaryType) && _deepEquals(primaryTypeDisplayName, other.primaryTypeDisplayName) && _deepEquals(rating, other.rating) && _deepEquals(userRatingCount, other.userRatingCount) && _deepEquals(priceLevel, other.priceLevel) && _deepEquals(nationalPhoneNumber, other.nationalPhoneNumber) && _deepEquals(internationalPhoneNumber, other.internationalPhoneNumber) && _deepEquals(websiteUri, other.websiteUri) && _deepEquals(googleMapsUri, other.googleMapsUri) && _deepEquals(utcOffsetMinutes, other.utcOffsetMinutes) && _deepEquals(businessStatus, other.businessStatus) && _deepEquals(editorialSummary, other.editorialSummary) && _deepEquals(regularOpeningHours, other.regularOpeningHours) && _deepEquals(photos, other.photos) && _deepEquals(reviews, other.reviews);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlaceMsg(id: $id, displayName: $displayName, formattedAddress: $formattedAddress, shortFormattedAddress: $shortFormattedAddress, location: $location, viewport: $viewport, addressComponents: $addressComponents, types: $types, primaryType: $primaryType, primaryTypeDisplayName: $primaryTypeDisplayName, rating: $rating, userRatingCount: $userRatingCount, priceLevel: $priceLevel, nationalPhoneNumber: $nationalPhoneNumber, internationalPhoneNumber: $internationalPhoneNumber, websiteUri: $websiteUri, googleMapsUri: $googleMapsUri, utcOffsetMinutes: $utcOffsetMinutes, businessStatus: $businessStatus, editorialSummary: $editorialSummary, regularOpeningHours: $regularOpeningHours, photos: $photos, reviews: $reviews)';
  }
}

class PhotoDataMsg {
  PhotoDataMsg({
    this.bytes,
    this.uri,
  });

  Uint8List? bytes;

  String? uri;

  List<Object?> _toList() {
    return <Object?>[
      bytes,
      uri,
    ];
  }

  Object encode() {
    return _toList();  }

  static PhotoDataMsg decode(Object result) {
    result as List<Object?>;
    return PhotoDataMsg(
      bytes: result[0] as Uint8List?,
      uri: result[1] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PhotoDataMsg || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(bytes, other.bytes) && _deepEquals(uri, other.uri);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PhotoDataMsg(bytes: $bytes, uri: $uri)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is LatLngMsg) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is LatLngBoundsMsg) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is AreaMsg) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is OptionsMsg) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is MatchedRangeMsg) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is PredictionMsg) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is AddressComponentMsg) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    }    else if (value is TimePointMsg) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    }    else if (value is OpeningPeriodMsg) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    }    else if (value is OpeningHoursMsg) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    }    else if (value is AuthorAttributionMsg) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    }    else if (value is PhotoRefMsg) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    }    else if (value is ReviewMsg) {
      buffer.putUint8(141);
      writeValue(buffer, value.encode());
    }    else if (value is PlaceMsg) {
      buffer.putUint8(142);
      writeValue(buffer, value.encode());
    }    else if (value is PhotoDataMsg) {
      buffer.putUint8(143);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return LatLngMsg.decode(readValue(buffer)!);
      case 130:
        return LatLngBoundsMsg.decode(readValue(buffer)!);
      case 131:
        return AreaMsg.decode(readValue(buffer)!);
      case 132:
        return OptionsMsg.decode(readValue(buffer)!);
      case 133:
        return MatchedRangeMsg.decode(readValue(buffer)!);
      case 134:
        return PredictionMsg.decode(readValue(buffer)!);
      case 135:
        return AddressComponentMsg.decode(readValue(buffer)!);
      case 136:
        return TimePointMsg.decode(readValue(buffer)!);
      case 137:
        return OpeningPeriodMsg.decode(readValue(buffer)!);
      case 138:
        return OpeningHoursMsg.decode(readValue(buffer)!);
      case 139:
        return AuthorAttributionMsg.decode(readValue(buffer)!);
      case 140:
        return PhotoRefMsg.decode(readValue(buffer)!);
      case 141:
        return ReviewMsg.decode(readValue(buffer)!);
      case 142:
        return PlaceMsg.decode(readValue(buffer)!);
      case 143:
        return PhotoDataMsg.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class PlacesHostApi {
  /// Constructor for [PlacesHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  PlacesHostApi({
      BinaryMessenger? binaryMessenger, 
      String messageChannelSuffix = '', 
      })
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';

  final BinaryMessenger? pigeonVar_binaryMessenger;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;


  /// Initializes the native SDK once, before the first Places call.
  ///
  /// [apiKey] is the key resolved from `--dart-define` (null when none was
  /// given); a null/blank value falls back to the native configuration
  /// (AndroidManifest meta-data / Info.plist). Throws
  /// FlutterError(invalidApiKey) when no key is found anywhere.
  Future<void> initialize(String? apiKey) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.fl_place_autocomplete_platform_interface.PlacesHostApi.initialize$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[apiKey]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Drops the native session token for [sessionId], if any.
  Future<void> disposeSession(String sessionId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.fl_place_autocomplete_platform_interface.PlacesHostApi.disposeSession$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[sessionId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<List<PredictionMsg>> findPredictions(String input, String? sessionId, OptionsMsg options) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.fl_place_autocomplete_platform_interface.PlacesHostApi.findPredictions$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[input, sessionId, options]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<PredictionMsg>();
  }

  Future<PlaceMsg> fetchPlace(String placeId, String? sessionId, List<String> fields, String? languageCode, String? regionCode) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.fl_place_autocomplete_platform_interface.PlacesHostApi.fetchPlace$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[placeId, sessionId, fields, languageCode, regionCode]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as PlaceMsg;
  }

  Future<PhotoDataMsg> fetchPhoto(PhotoRefMsg ref, int? maxWidth, int? maxHeight) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.fl_place_autocomplete_platform_interface.PlacesHostApi.fetchPhoto$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[ref, maxWidth, maxHeight]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as PhotoDataMsg;
  }
}
