name: fl_place_autocomplete_ios
description: "iOS implementation of fl_place_autocomplete."
version: 0.1.0
homepage: https://github.com/kishormainali/fl_place_autocomplete
repository: https://github.com/kishormainali/fl_place_autocomplete/tree/main/fl_place_autocomplete_ios
issue_tracker: https://github.com/kishormainali/fl_place_autocomplete/issues
topics:
  - google-places
  - places
  - autocomplete
  - ios

environment:
  sdk: ^3.13.0
  flutter: ">=3.44.0"
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  fl_place_autocomplete_platform_interface: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    implements: fl_place_autocomplete
    platforms:
      ios:
        pluginClass: FlPlaceAutocompleteIosPlugin
        dartPluginClass: FlPlaceAutocompleteIos
